import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import GenerateStealthSafeAccounts from "../components/GenerateStealthSafeAccounts";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-col space-y-12 justify-between items-center">
          <ConnectButton />
          <GenerateStealthSafeAccounts />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://builders.garden"
          rel="noopener noreferrer"
          target="_blank"
        >
          Made with ❤️ by builders garden 🌳
        </a>
      </footer>
    </div>
  );
};

export default Home;
